# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Roblox Messages to PDF
tagline:          'A PDF Generator for Roblox!'
description:      'A generator which takes your Roblox Messages and turns them into a PDF</a> Made by <a href="https://twitter.com/Coldreactor64" target="_blank">@Coldreactor64</a>.'
url:              http://coldreactor.me/Roblox-Messages-to-PDF
baseurl: /Roblox-Messages-to-PDF/
linkurl: /Roblox-Messages-to-PDF
author:
  name:           'Jeremy Hall'
  url:            https://twitter.com/Coldreactor64

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/coldreactor64/Roblox-Messages-to-PDF


plugins: [jekyll-paginate]